apiVersion: v1
kind: Service
metadata:
  name: switchboard
spec:
  selector:
    app: switchboard
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: {{ .Values.service.type }}
